### ISSUE TITLE
Waffle 3 Roadmap

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#155]
# Roadmap for future Waffle releases

Note that even though these are features for Waffle 3 we will be rolling them out as part of Waffle 2, issuing deprecation messages when necessary.

## Milestone 1
- [x] Add dynamic Smart Contracts mocking (#109)
- [x] Use truffle-flattener from CLI for convince (#156)
- [x] Configuration improvements (see below)
- [x] Add support for ENS (#197)
- [x] Mock matchers expect(...).to.be.called (#229)

## Milestone 2
- [ ] Documentation: Examples on recurring patterns and solutions (optional)
- [x] New matchers (#9) (optional)
- [x] Enable minimal output (abi and bytecode only)
- [x] Waffle 2 to Waffle 3 migration guide
- [x] Upgrade to Ethers.js 5.x

## No milestone
- [x] `provider.getWallets()` or `getWallets()` without `provider`
- [x] replace `createMockProvider` with `new MockProvider(options)`
- [x] Support for Vyper
- [ ] Show file and line of revert (#225 )

## Configuration improvements:
- [x] Migrate to a monorepo structure (#167)
- [x] Update `waffle.json` config file schema (#166)
- [x] Simplify specifying solc version in configuration

## Planned breaking Changes in Waffle 3.0
- [x] Remove deprecated APIs (#256 )
- [x] Swap arguments in loadFixture and make provider optional (Issue #116, PR #215)
- [x] Automatically recognise `.waffle.json` config without cli argument
- [x] Introduce MockProviderOptions (instead of Ganache options) in MockProvider constructor
- [x] drop support for `contract.interface`

## Package improvements
- [x] Migrate to CircleCi
- [x] Correctly configure build output (#164)
- [x] Do not include unnecessary files in the resulting npm package (#164)

## Optional
- [ ] Add a custom provider based on ethereumjs-vm
- [ ] Explore having built in utility contracts (optional)

## Promotion:
- Blog posts on Waffle update (when new features released)
- Blog post series on advanced testing techniuqes
  - [ ] Fixture
  - [x] Dynamic mocking
  - [ ] ENS mocking
  - [ ] Waffle configuration tutorial
- Presentations
  - [ ] Apply for Devcon
  - [ ] Apply for EthBerlin/Dappcon

**Comment by marekkirejczyk** [comment]
version 3 released

**Comment by RostyslavDzhohola** [comment]
I have an issue with installing "npm i ethereum-waffle". 
It cannot find bunch of files in the node-modules 
Example: 
[2020-10-15T18_00_02_936Z-debug.log](https://github.com/EthWorks/Waffle/files/5386931/2020-10-15T18_00_02_936Z-debug.log)
`npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Rostyslav\AppData\Roaming\VS-Projects\buidler-tutorial\node_modules\.staging\ethashjs-8a961820\.pretti
[2020-10-15T18_12_12_197Z-debug.log](https://github.com/EthWorks/Waffle/files/5386933/2020-10-15T18_12_12_197Z-debug.log)
errc'`

I have followed instructions from https://buidler.dev/tutorial/writing-and-compiling-contracts.html 
Please advice.
